[package]
name = "amm-contract"
version = "0.1.1"
authors = ["S T"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { path = "../near-sdk-rs/near-sdk" }
near-contract-standards = { path = "../near-sdk-rs/near-contract-standards" }

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true